### ISSUE TITLE
Hasil pencarian dobel

### ISSUE THREAD

**Issue by abrari** [lafzi/lafzi-android#11]
Hasilnya cuma satu tapi ditampilkan dua.

<img src="https://cloud.githubusercontent.com/assets/7134480/25562338/e65817ae-2dad-11e7-800c-7dc239c6f9f4.png" alt="bug" width="300"/>

Steps to reproduce:
1. Jalankan (saya coba di emulator)
2. Masukkan query "iqra bismi"
3. Submit
4. Ulangi pencarian beberapa kali (submit lagi dan lagi)
5. Terkadang muncul satu, terkadang muncul dua

**Comment by harunalfat** [comment]
Issue muncul karena penggunaan tombol enter pada keyboard untuk submit (entah kenapa tombol enter jadi kesubmit 2 kali). Masih dicari penyebabnya.

Harusnya untuk perangkat gadget asli tidak ada issue

**Comment by abrari** [comment]
Oh bisa ngaruh ya. Belum coba di device beneran sih. Kalau di device nggak masalah bisa close aja ini.
