### ISSUE TITLE
TODO list untuk publish playstore

### ISSUE THREAD

**Issue by harunalfat** [lafzi/lafzi-android#13]
Dari Play Store ada persyaratan

* ~You need to add a high-res icon. [Indonesian – id]~
* ~You need to add a feature graphic. [Indonesian – id]~
* ~You need to add at least 2 non-Android TV screenshots. [Indonesian – id]~
* ~You need to select a category.~
* ~You need to add a short description. [Indonesian – id]~
* ~You need to add a full description. [Indonesian – id]~
* You need to upload an APK for this application.
* You need to target at least one country.
* ~You need to enter a privacy policy URL.~
* You need to make your application free or set a price for it.
* You need to declare whether or not your application contains ads.
* Your app is missing a required content rating. Go to your app's Content Rating page and complete a rating questionnaire.

Mungkin bisa dicicil perlahan di Google Play Console

**Comment by harunalfat** [comment]
Bisa diganti di Google Play Console kalau ada yang tidak sesuai

**Comment by abrari** [comment]
Perlu bikin versi beta nggak buat testing?

https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

**Comment by harunalfat** [comment]
Saya sih terserah kak Abrar baiknya gimana :smile:, apa kita kumpul feedback dulu, atau langsung publish

**Comment by harunalfat** [comment]
Kak Abrar, bisa minta svg hi-res dari Lafzi icon dan Lafzi splash ga? :smile:

**Comment by abrari** [comment]
Ada di sini @harunalfat: https://raw.githubusercontent.com/lafzi/lafzi-web/master/web/res/mockup.svg

Perlu punya font "KacstScreen".

Buat beta test saya kasih ke beberapa dosen Ilkom aja nanti ya :smile:

**Comment by harunalfat** [comment]
Released on play store 😁
