### ISSUE TITLE
Layout bantuan muncul ketika search

### ISSUE THREAD

**Issue by harunalfat** [lafzi/lafzi-android#14]
![cropped](https://cloud.githubusercontent.com/assets/12376870/25569141/fa080fce-2e3a-11e7-8752-1547c0e7e199.png)

1. Search dengan kata kunci yang butuh pencarian lama (misal Allah)
2. Layout bantuan muncul di bawah progress bar. Seharusnya tidak

**Comment by abrari** [comment]
Btw, mau dibatasin nggak jumlah maksimal hasil pencarian yang tampil?
