### ISSUE TITLE
Nama package (com.lafzi.lafzi)

### ISSUE THREAD

**Issue by abrari** [lafzi/lafzi-android#3]
Agak redundan :grin:

Saran mungkin kalau bisa di-refactor jadi misalnya `com.lafzi.android`.

**Comment by harunalfat** [comment]
hahaha, sebenarnya sih kepikiran siapa tau Lafzi bakal punya produk lain :roll_eyes: selain "Lafzi" (you know what I mean :v)

nanti di-rename deh :+1:

**Comment by harunalfat** [comment]
Fixed in 270fb6f558e13cc8b4749161dd65871d31c25bc9
