### ISSUE TITLE
Infinite loop untuk query tertentu

### ISSUE THREAD

**Issue by abrari** [lafzi/lafzi-android#6]
Waktu iseng coba dengan query aneh "zzzzzzzzzzzzzzzz", aplikasi sepertinya stuck di progress dialog pencarian. Sepertinya karena query tersebut ketika dinormalisasi cuma jadi "Z" saja dan tidak memenuhi satu trigram.

Expected result: tidak ada hasil ([seperti ini](http://lafzi.apps.cs.ipb.ac.id/web/search.php?q=zzzzzzzzzzzzzzzzzzz&vowel=on))
Actual result: stuck di pencarian

Dicoba dengan query misal "bbbbbbbzzzzzzzzz" juga demikian.

Sepertinya setelah query dinormalisasi harus dicek apakah hasilnya >= 3 karakter. Kalau tidak maka respon tidak ada hasil.

**Comment by harunalfat** [comment]
Fixed within 161ea74d21faa07c18cae0f03e8b41458d69780e
