### ISSUE TITLE
Database pre-populated

### ISSUE THREAD

**Issue by abrari** [lafzi/lafzi-android#8]
Supaya tidak perlu migrate saat pertama kali aplikasi dijalankan di device*), database sqlite-nya sebaiknya sudah dibuat sebelumnya dan di-load sebagai aset [pakai ini](https://github.com/jgilfelt/android-sqlite-asset-helper).

Database terbaru (saat ini) ada di repo lafzi/lafzi-indexer#8 (v3.sqlite).

*) Di emulator crash waktu pertama kali dijalankan. Tapi ketika dijalankan lagi kedua kalinya baru jalan proses migrate-nya.

**Comment by abrari** [comment]
Database indeks `lafzi.sqlite` sudah diperbarui ([indeks v4](https://github.com/lafzi/lafzi-indexer/tree/v4/index)).

**Comment by harunalfat** [comment]
Added di 161ea74d21faa07c18cae0f03e8b41458d69780e
